// Kevin Zhang — Super Cool Website
const $ = s => document.querySelector(s);

// 1) Particle simulation
const pc = $('#particleCanvas'), pctx = pc.getContext('2d'); let running=true, particles=[];
function resizeCanvas(c){ const r=c.getBoundingClientRect(), d=devicePixelRatio||1; c.width=Math.max(320,r.width*d); c.height=Math.max(200,(r.width*0.56)*d); }
function newParticle(){return{x:Math.random()*pc.width,y:Math.random()*pc.height*.7,vx:(Math.random()-.5)*7,vy:(Math.random()-.5)*5,r:7+Math.random()*10,h:Math.floor(Math.random()*300+30)}}
function resetParticles(){particles=Array.from({length:26},newParticle)}
function particleFrame(){if(running){pctx.clearRect(0,0,pc.width,pc.height);const g=+$('#gravity').value*(devicePixelRatio||1);particles.forEach(p=>{p.vy+=g;p.x+=p.vx;p.y+=p.vy;if(p.x<p.r||p.x>pc.width-p.r){p.vx*=-.92;p.x=Math.max(p.r,Math.min(pc.width-p.r,p.x))}if(p.y>pc.height-p.r){p.y=pc.height-p.r;p.vy*=-.78}if(p.y<p.r){p.y=p.r;p.vy=Math.abs(p.vy)}pctx.beginPath();pctx.arc(p.x,p.y,p.r,0,Math.PI*2);pctx.fillStyle=`hsl(${p.h} 85% 62%)`;pctx.fill()})}requestAnimationFrame(particleFrame)}
resizeCanvas(pc);resetParticles();particleFrame();$('#particleToggle').onclick=()=>{running=!running;$('#particleToggle').textContent=running?'Pause':'Play'};$('#particleBurst').onclick=()=>particles.push(...Array.from({length:15},newParticle));$('#particleClear').onclick=resetParticles;

// 2) Homework tracker — browser local storage
let tasks=JSON.parse(localStorage.getItem('kzTasks')||'[]');
function renderTasks(){const ul=$('#taskList');ul.innerHTML='';tasks.forEach((t,i)=>{const li=document.createElement('li');if(t.done)li.classList.add('done');li.innerHTML=`<input type="checkbox" ${t.done?'checked':''} aria-label="Mark task complete"><span></span><button class="delete" aria-label="Delete task">×</button>`;li.querySelector('span').textContent=t.text;li.querySelector('input').onchange=e=>{tasks[i].done=e.target.checked;saveTasks()};li.querySelector('.delete').onclick=()=>{tasks.splice(i,1);saveTasks()};ul.append(li)});const done=tasks.filter(t=>t.done).length;$('#taskProgress').textContent=`${done} of ${tasks.length} complete`}
function saveTasks(){localStorage.setItem('kzTasks',JSON.stringify(tasks));renderTasks()}renderTasks();$('#taskForm').onsubmit=e=>{e.preventDefault();const v=$('#taskInput').value.trim();if(v){tasks.push({text:v,done:false});$('#taskInput').value='';saveTasks()}};$('#clearDone').onclick=()=>{tasks=tasks.filter(t=>!t.done);saveTasks()};

// 3) Study timer
let total=1500,left=1500,tick=null;function showTime(){const m=Math.floor(left/60),s=left%60;$('#timerDisplay').textContent=`${m}:${String(s).padStart(2,'0')}`;const deg=total?360*(1-left/total):0;document.querySelector('.timer-ring').style.background=`conic-gradient(var(--accent) 0 ${deg}deg,var(--line) ${deg}deg)`}function stopTimer(){clearInterval(tick);tick=null;$('#timerStart').textContent='Start';$('#timerStatus').textContent=left===0?'DONE!':'PAUSED'}$('#timerStart').onclick=()=>{if(tick){stopTimer();return}if(left===0)left=total;$('#timerStart').textContent='Pause';$('#timerStatus').textContent='FOCUS';tick=setInterval(()=>{left--;showTime();if(left<=0){left=0;showTime();stopTimer()}},1000)};$('#timerReset').onclick=()=>{stopTimer();left=total;$('#timerStatus').textContent='READY';showTime()};$('#timerPreset').onchange=e=>{stopTimer();total=left=+e.target.value;showTime()};showTime();

// 4) Reaction game
let reactionTimeout=null,reactionStartTime=0,reactionReady=false,best=+(localStorage.getItem('kzBestReaction')||0);if(best)$('#bestReaction').textContent=best+' ms';function startReaction(){clearTimeout(reactionTimeout);reactionReady=false;$('#target').style.display='none';$('#reactionMessage').innerHTML='Wait for it… <b>don’t click early!</b>';reactionTimeout=setTimeout(()=>{reactionReady=true;const arena=$('#reactionArena'),t=$('#target');const maxX=arena.clientWidth-75,maxY=arena.clientHeight-75;t.style.left=(8+Math.random()*Math.max(10,maxX-8))+'px';t.style.top=(8+Math.random()*Math.max(10,maxY-8))+'px';t.style.display='block';reactionStartTime=performance.now();$('#reactionMessage').textContent=''},900+Math.random()*2500)}$('#reactionStart').onclick=startReaction;$('#target').onclick=e=>{e.stopPropagation();if(!reactionReady)return;const ms=Math.round(performance.now()-reactionStartTime);reactionReady=false;$('#target').style.display='none';$('#latestReaction').textContent=ms+' ms';if(!best||ms<best){best=ms;localStorage.setItem('kzBestReaction',best);$('#bestReaction').textContent=best+' ms'}$('#reactionMessage').innerHTML=`Nice! <b>${ms} ms</b>. Start another round.`};$('#reactionArena').onclick=()=>{if(!reactionReady&&reactionTimeout){clearTimeout(reactionTimeout);reactionTimeout=null;$('#reactionMessage').innerHTML='Too early! 😄 Press <b>Start Round</b> again.'}}

// 5) Geometry visualizer
const gc=$('#geometryCanvas'),g=gc.getContext('2d');function drawGeometry(){resizeCanvas(gc);const shape=$('#shapeSelect').value,size=+$('#shapeSize').value*(devicePixelRatio||1),cx=gc.width/2,cy=gc.height/2;g.clearRect(0,0,gc.width,gc.height);g.lineWidth=5*(devicePixelRatio||1);g.strokeStyle=getComputedStyle(document.body).getPropertyValue('--accent').trim()||'#7c6cff';g.fillStyle='rgba(124,108,255,.15)';let text='';g.beginPath();if(shape==='Circle'){g.arc(cx,cy,size,0,Math.PI*2);text=`Radius: ${Math.round(size/(devicePixelRatio||1))}<br>Diameter: ${Math.round(size*2/(devicePixelRatio||1))}<br>Area: ${Math.round(Math.PI*(size/(devicePixelRatio||1))**2)}<br>Circumference: ${Math.round(2*Math.PI*size/(devicePixelRatio||1))}`}else if(shape==='Rectangle'){const w=size*1.5,h=size;g.rect(cx-w/2,cy-h/2,w,h);text=`Width: ${Math.round(w/(devicePixelRatio||1))}<br>Height: ${Math.round(h/(devicePixelRatio||1))}<br>Area: ${Math.round(w*h/(devicePixelRatio||1)**2)}<br>Perimeter: ${Math.round(2*(w+h)/(devicePixelRatio||1))}`}else{const h=size*1.5;g.moveTo(cx,cy-h/2);g.lineTo(cx-size,cy+h/2);g.lineTo(cx+size,cy+h/2);g.closePath();text=`Base: ${Math.round(size*2/(devicePixelRatio||1))}<br>Height: ${Math.round(h/(devicePixelRatio||1))}<br>Area: ${Math.round(size*h/(devicePixelRatio||1)**2)}`}g.fill();g.stroke();$('#shapeStats').innerHTML=text}$('#shapeSelect').onchange=drawGeometry;$('#shapeSize').oninput=drawGeometry;drawGeometry();

// 6) Filterable gallery — generated artwork, easy to replace with real photos later
const gallery=[['Aurora Ridge','nature','linear-gradient(135deg,#04a,#5ff,#183)'],['Pixel City','tech','linear-gradient(135deg,#512da8,#00bcd4,#ff4081)'],['Nebula Run','space','radial-gradient(circle at 30% 30%,#fff 0 2%,transparent 3%),linear-gradient(135deg,#05051b,#6b2d9c,#ff6f91)'],['Golden Trail','nature','linear-gradient(135deg,#243,#edb75a,#773)'],['Circuit Glow','tech','repeating-linear-gradient(45deg,#102030 0 12px,#19d2aa 12px 15px,#102030 15px 26px)'],['Blue Planet','space','radial-gradient(circle at 60% 45%,#36d 0 28%,#07101f 29% 100%)']];
function renderGallery(filter='all'){const grid=$('#galleryGrid');grid.innerHTML='';gallery.filter(x=>filter==='all'||x[1]===filter).forEach(([title,cat,art])=>{const d=document.createElement('div');d.className='gallery-item';d.style.setProperty('--art',art);d.innerHTML=`<span>${title}</span>`;d.onclick=()=>{$('#modalImage').style.background=art;$('#modalImage').src='data:image/svg+xml,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="900" height="560"><rect width="100%" height="100%" fill="#111"/></svg>`);$('#modalTitle').textContent=title;$('#modalText').textContent=`${cat[0].toUpperCase()+cat.slice(1)} gallery artwork. Replace this placeholder with Kevin’s own photo anytime.`;$('#galleryModal').showModal()};grid.append(d)})}renderGallery();document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderGallery(b.dataset.filter)});$('#modalClose').onclick=()=>$('#galleryModal').close();

// Bonus: counter
let count=+(localStorage.getItem('kzCounter')||0);$('#countValue').textContent=count;$('#countBtn').onclick=()=>{$('#countValue').textContent=++count;localStorage.setItem('kzCounter',count)};$('#countReset').onclick=()=>{count=0;$('#countValue').textContent=0;localStorage.setItem('kzCounter',0)};
// Bonus: themes
const themes=[['','Midnight Neon'],['theme-sunset','Sunset Arcade'],['theme-ice','Ice Lab']];let themeIndex=+(localStorage.getItem('kzTheme')||0);function applyTheme(){document.body.className=themes[themeIndex][0];$('#themeName').textContent=themes[themeIndex][1];drawGeometry()}applyTheme();$('#themeBtn').onclick=()=>{themeIndex=(themeIndex+1)%themes.length;localStorage.setItem('kzTheme',themeIndex);applyTheme()};
// Bonus: kid-safe luck game
const symbols=['★','◆','●','▲','☀'];$('#luckBtn').onclick=()=>{const picks=Array.from({length:3},()=>symbols[Math.floor(Math.random()*symbols.length)]);$('#slot').textContent=picks.join(' ');const match=new Set(picks).size;$('#luckResult').textContent=match===1?'SUPER LUCKY! Three match!':match===2?'Nice! Two match.':'Try again — pure random fun!'};
window.addEventListener('resize',()=>{resizeCanvas(pc);drawGeometry()});
